/* French translations — keys are the English source strings. */
export const fr: Record<string, string> = {
  '+ New page': '+ Nouvelle page',
  '24 hours': '24 heures',
  '30 days': '30 jours',
  '50% of everyone else': '50 % des autres visiteurs',
  '7 days': '7 jours',
  '90 days': '90 jours',
  'A profile that opens doors.': 'Un profil qui ouvre des portes.',
  'A short link is created for it, so you can change the destination later.':
    'Un lien court est créé pour lui : vous pourrez changer la destination plus tard.',
  'A to Z': 'De A à Z',
  'A/B test': 'Test A/B',
  API: 'API',
  'API keys': "Clés d'API",
  'API keys are disabled in the demo workspace.': "Les clés d'API sont désactivées dans l'espace démo.",
  'API reference': "Référence de l'API",
  About: 'À propos',
  'Accepting responses': 'Réponses ouvertes',
  'Access and limits': 'Accès et limites',
  Account: 'Compte',
  Active: 'Actifs',
  'Add UTM parameters': 'Ajouter des paramètres UTM',
  'Add UTM tags once; every destination inherits them.':
    'Ajoutez vos UTM une fois : toutes les destinations en héritent.',
  'Add a link': 'Ajouter un lien',
  'Add a logo': 'Ajouter un logo',
  'Add a rule': 'Ajouter une règle',
  'Add a variant': 'Ajouter une variante',
  Address: 'Adresse',
  All: 'Tout',
  'All clicks': 'Tous les clics',
  'All links': 'Tous les liens',
  'All opportunities': 'Toutes les opportunités',
  'All tags': 'Tous les tags',
  'Already have an account?': 'Déjà un compte ?',
  'Android visitors': 'Visiteurs Android',
  Angle: 'Angle',
  'Another website': 'Un autre site',
  'Appearance and language': 'Apparence et langue',
  Application: 'Candidature',
  Archive: 'Archiver',
  Archived: 'Archivés',
  'At least 8 characters.': '8 caractères minimum.',
  'Backend engineer (Node.js)': 'Ingénieur backend (Node.js)',
  Background: 'Fond',
  'Browse the directory': "Parcourir l'annuaire",
  Browsers: 'Navigateurs',
  'Built by Imrane Adli on Cloudflare Workers.': 'Conçu par Imrane Adli sur Cloudflare Workers.',
  'Built for developers, too.': 'Pensé aussi pour les développeurs.',
  'Business card details': 'Coordonnées de la carte de visite',
  'CTO at Rocket Labs': 'CTO chez Rocket Labs',
  'Campaign tracking (UTM)': 'Suivi de campagne (UTM)',
  Change: 'Modifier',
  'Change language': 'Changer de langue',
  Channels: 'Canaux',
  'Choose a CSV file': 'Choisir un fichier CSV',
  'Choose a link…': 'Choisir un lien…',
  Cities: 'Villes',
  'City or region': 'Ville ou région',
  'Clear the filters to see everything that is open right now.':
    'Retirez les filtres pour voir tout ce qui est ouvert en ce moment.',
  Clicks: 'Clics',
  'Clicks by country': 'Clics par pays',
  'Clicks over time': 'Clics dans le temps',
  Close: 'Fermer',
  'Close it when the position is filled; the page stays online.':
    'Fermez-la une fois le poste pourvu ; la page reste en ligne.',
  Closed: 'Fermée',
  'Co-founder': 'Cofondateur',
  Code: 'Code',
  'Code and background need more contrast to scan.':
    'Le code et le fond manquent de contraste pour être scannés.',
  Collaboration: 'Collaboration',
  Colours: 'Couleurs',
  'Command palette': 'Palette de commandes',
  Companies: 'Entreprises',
  Company: 'Entreprise',
  'Company (optional)': 'Entreprise (facultatif)',
  Computer: 'Ordinateur',
  Connect: 'Réseau',
  Continue: 'Continuer',
  Copied: 'Copié',
  Copy: 'Copier',
  'Copy link': 'Copier le lien',
  'Copy this key now. For your security it will not be shown again.':
    'Copiez cette clé maintenant. Pour votre sécurité, elle ne sera plus affichée.',
  Corners: 'Coins',
  Countries: 'Pays',
  'Country codes': 'Codes pays',
  'Create QR code': 'Créer le QR code',
  'Create a free account': 'Créer un compte gratuit',
  'Create a link': 'Créer un lien',
  'Create account': 'Créer le compte',
  'Create an account': 'Créer un compte',
  'Create key': 'Créer la clé',
  'Create link': 'Créer le lien',
  'Create your account': 'Créez votre compte',
  'Create your first short link': 'Créez votre premier lien court',
  'Create your own account': 'Créer votre propre compte',
  'Create your profile': 'Créez votre profil',
  'Create your profile first': "Créez d'abord votre profil",
  'Created {d}': 'Créé le {d}',
  'Current password': 'Mot de passe actuel',
  Dark: 'Sombre',
  'Dark mode': 'Mode sombre',
  Delete: 'Supprimer',
  'Delete /{slug} and all of its analytics? This cannot be undone.':
    "Supprimer /{slug} et toutes ses statistiques ? C'est définitif.",
  'Delete account': 'Supprimer le compte',
  'Delete my account': 'Supprimer mon compte',
  'Delete page': 'Supprimer la page',
  'Delete this QR code? Printed copies will keep working through the short link.':
    'Supprimer ce QR code ? Les exemplaires imprimés continueront de fonctionner grâce au lien court.',
  'Delete this message?': 'Supprimer ce message ?',
  'Delete this opportunity?': 'Supprimer cette opportunité ?',
  'Delete this page, its opportunities and its inbox?':
    'Supprimer cette page, ses opportunités et sa boîte de réception ?',
  'Delete your account and everything in it? This cannot be undone.':
    "Supprimer votre compte et tout son contenu ? C'est définitif.",
  'Deletes your links, QR codes, profiles, opportunities and messages. Short links stop working immediately.':
    'Supprime vos liens, QR codes, profils, opportunités et messages. Les liens courts cessent immédiatement de fonctionner.',
  Description: 'Description',
  'Design a QR code': 'Créer un QR code',
  'Design your first QR code': 'Créez votre premier QR code',
  Desktop: 'Ordinateur',
  Destination: 'Destination',
  'Destination URL': 'URL de destination',
  Devices: 'Appareils',
  'Direct or typed': 'Direct ou saisi',
  Discover: 'Découvrir',
  'Discover people and startups': 'Découvrir des profils et des startups',
  Done: 'Terminé',
  Dots: 'Points',
  'Download my QR business card': 'Télécharger ma carte de visite QR',
  Edit: 'Modifier',
  'Edit /{slug}': 'Modifier /{slug}',
  'Edit QR code': 'Modifier le QR code',
  'Edit opportunity': "Modifier l'opportunité",
  Email: 'E-mail',
  'Enter the password you were given to continue.':
    "Saisissez le mot de passe qu'on vous a donné pour continuer.",
  'Every WRX QR code is dynamic: it encodes a short link, so menus, posters and business cards never need reprinting.':
    "Chaque QR code WRX est dynamique : il contient un lien court, donc menus, affiches et cartes de visite n'ont jamais besoin d'être réimprimés.",
  'Every code is dynamic: change its destination later without reprinting it.':
    'Chaque code est dynamique : changez sa destination plus tard sans le réimprimer.',
  'Every feature is available through a documented REST API. Create a key in Settings and you are one request away from a short link.':
    "Toutes les fonctionnalités sont disponibles via une API REST documentée. Créez une clé dans les réglages : un lien court n'est qu'à une requête.",
  Everyone: 'Tout le monde',
  'Everyone else': 'Tous les autres',
  Expires: 'Expire',
  'Explore the demo instead': 'Explorer plutôt la démo',
  'Explore the live demo': 'Explorer la démo',
  'Export a CSV with a header row. Required column: url. Optional: slug, title, tags (separate tags with |). Up to 500 rows.':
    "Exportez un CSV avec une ligne d'en-tête. Colonne obligatoire : url. Facultatives : slug, title, tags (séparez les tags par |). 500 lignes maximum.",
  Filter: 'Filtrer',
  'Filter by tag': 'Filtrer par tag',
  'Find developers, designers and founders, startups looking for co-founders or funding, and companies that are hiring. Send an introduction in one message.':
    'Trouvez des développeurs, des designers et des fondateurs, des startups qui cherchent un cofondateur ou des fonds, et des entreprises qui recrutent. Présentez-vous en un message.',
  Focus: 'Domaines',
  'Focus areas': "Domaines d'expertise",
  'For example: Full-stack developer, React and Node.js':
    'Par exemple : Développeur full-stack, React et Node.js',
  'For example: Online booking for clinics — seed stage':
    "Par exemple : Réservation en ligne pour cliniques — phase d'amorçage",
  Frame: 'Cadre',
  'Frame text': 'Texte du cadre',
  'Free forever for personal use. No card needed.': 'Gratuit pour un usage personnel. Sans carte bancaire.',
  Freelance: 'Freelance',
  'Freelance mission': 'Mission freelance',
  'Full name': 'Nom complet',
  Funding: 'Levée de fonds',
  'Get in touch': 'Prendre contact',
  'Go to the home page': "Aller à l'accueil",
  'Good afternoon': 'Bon après-midi',
  'Good evening': 'Bonsoir',
  'Good morning': 'Bonjour',
  'Google Analytics and similar tools will attribute visits to this campaign.':
    'Google Analytics et les outils similaires attribueront les visites à cette campagne.',
  Gradient: 'Dégradé',
  Headline: 'Titre',
  'Here is how your links are doing.': 'Voici comment se portent vos liens.',
  Hiring: 'Recrute',
  'How they arrive': "D'où ils viennent",
  'I want to hire you': 'Je souhaite vous recruter',
  'If the visitor is in': 'Si le visiteur est en/au',
  'If the visitor uses': 'Si le visiteur utilise',
  'If you expected it to work, ask the person who shared it for a new link.':
    "Si vous pensiez qu'il fonctionnait, demandez un nouveau lien à la personne qui l'a partagé.",
  Import: 'Importer',
  'Import 500 links from a spreadsheet, or create them from the REST API.':
    "Importez 500 liens depuis un tableur, ou créez-les via l'API REST.",
  'Import CSV': 'Importer un CSV',
  'Import links from a spreadsheet': 'Importer des liens depuis un tableur',
  'Import {n} links': 'Importer {n} liens',
  'In progress': 'En cours',
  Inbox: 'Messages',
  Industry: 'Secteur',
  Internship: 'Stage',
  Internships: 'Stages',
  'Introduce your startup': 'Présentez votre startup',
  'Introductions, applications and proposals sent from your profile and opportunities.':
    'Présentations, candidatures et propositions envoyées depuis votre profil et vos opportunités.',
  Investment: 'Investissement',
  'It may have been mistyped, or its owner removed it.':
    "Il a peut-être été mal saisi, ou son propriétaire l'a supprimé.",
  'It takes two minutes. Choose whether you are a person, a startup or a company, and decide if you want to appear in the public directory.':
    "Deux minutes suffisent. Indiquez si vous êtes une personne, une startup ou une entreprise, et choisissez d'apparaître ou non dans l'annuaire public.",
  Job: 'Emploi',
  'Job application': 'Candidature',
  'Key name': 'Nom de la clé',
  'Key name, e.g. Zapier': 'Nom de la clé, par ex. Zapier',
  Label: 'Libellé',
  Language: 'Langue',
  'Latest clicks': 'Derniers clics',
  'Leave empty for a random one.': 'Laissez vide pour un nom aléatoire.',
  Light: 'Clair',
  'Light mode': 'Mode clair',
  Limited: 'Limité',
  Link: 'Lien',
  'Link archived': 'Lien archivé',
  'Link created — copied to your clipboard': 'Lien créé et copié dans le presse-papiers',
  'Link deleted': 'Lien supprimé',
  'Link restored': 'Lien restauré',
  'Link saved': 'Lien enregistré',
  Links: 'Liens',
  'Links on your page': 'Liens de votre page',
  'Live preview': 'Aperçu en direct',
  'Loading…': 'Chargement…',
  Location: 'Lieu',
  Look: 'Apparence',
  'Looking for a co-founder': 'Cherche un cofondateur',
  Main: 'Principal',
  'Make a QR code': 'Créer un QR code',
  'Maximum clicks': 'Clics maximum',
  'Meet the people building things.': 'Rencontrez celles et ceux qui construisent.',
  Mentoring: 'Mentorat',
  Message: 'Message',
  'Message sent': 'Message envoyé',
  Mobile: 'Mobile',
  'More actions': "Plus d'actions",
  'Most clicked': 'Plus cliqués',
  Name: 'Nom',
  'Name updated': 'Nom mis à jour',
  'Never used': 'Jamais utilisée',
  New: 'Nouveau',
  'New QR code': 'Nouveau QR code',
  'New destination': 'Nouvelle destination',
  'New password': 'Nouveau mot de passe',
  'New to WRX?': 'Nouveau sur WRX ?',
  'Newest first': 'Plus récents',
  'No clicks yet': "Aucun clic pour l'instant",
  'No data yet': 'Pas encore de données',
  'No frame': 'Sans cadre',
  'No link matches this search': 'Aucun lien ne correspond',
  'No messages yet': "Aucun message pour l'instant",
  'No open opportunities match': 'Aucune opportunité ouverte ne correspond',
  'No profiles match yet': 'Aucun profil ne correspond',
  'Nothing archived': "Rien d'archivé",
  'Nothing here': 'Rien ici',
  'Nothing matches “{q}”': 'Aucun résultat pour « {q} »',
  'Nothing posted yet': "Rien de publié pour l'instant",
  Off: 'Désactivé',
  On: 'Activé',
  'One link, the right destination for everyone.': 'Un lien, la bonne destination pour chacun.',
  'One of my links': 'Un de mes liens',
  'Only you see it.': 'Vous seul le voyez.',
  Open: 'Ouvrir',
  'Open dashboard': 'Ouvrir le tableau de bord',
  'Open menu': 'Ouvrir le menu',
  'Open opportunities': 'Opportunités ouvertes',
  'Open to': 'Ouvert à',
  'Open to anything': 'Ouvert à tout',
  'Open to everyone': 'Ouvert à tous',
  'Open to jobs': 'Ouvert aux offres',
  Opportunities: 'Opportunités',
  'Opportunities appear on your profile and in the Discover directory, with a shareable short link.':
    "Les opportunités apparaissent sur votre profil et dans l'annuaire, avec un lien court à partager.",
  'Opportunities are published by a profile.': 'Les opportunités sont publiées par un profil.',
  'Opportunity deleted': 'Opportunité supprimée',
  'Opportunity published': 'Opportunité publiée',
  'Opportunity saved': 'Opportunité enregistrée',
  Other: 'Autre',
  'Outline with label': 'Contour avec texte',
  Overview: "Vue d'ensemble",
  Partnership: 'Partenariat',
  Partnerships: 'Partenariats',
  Password: 'Mot de passe',
  'Password changed': 'Mot de passe modifié',
  'Password protected': 'Protégé par mot de passe',
  'Password-protect a link, or close it after a date or a number of clicks.':
    'Protégez un lien par mot de passe, ou fermez-le après une date ou un nombre de clics.',
  'Paste a long URL and get a short one you can share, track and turn into a QR code.':
    'Collez une URL longue et obtenez un lien court à partager, suivre et transformer en QR code.',
  'Paste any link': 'Collez un lien',
  People: 'Personnes',
  Period: 'Période',
  Person: 'Personne',
  Phone: 'Téléphone',
  'Pick colours, add your logo and a frame, then download it for print or screens.':
    "Choisissez les couleurs, ajoutez votre logo et un cadre, puis téléchargez-le pour l'impression ou l'écran.",
  'Post a job, an internship, a freelance mission, a co-founder search, a partnership or a funding round. Answers arrive in your inbox.':
    'Publiez un emploi, un stage, une mission freelance, une recherche de cofondateur, un partenariat ou une levée de fonds. Les réponses arrivent dans vos messages.',
  'Post an opportunity': 'Publier une opportunité',
  'Posted {when}': 'Publiée {when}',
  Preview: 'Aperçu',
  'Print a QR code once. Change where it points whenever you like.':
    'Imprimez un QR code une fois. Changez sa destination quand vous voulez.',
  Profile: 'Profil',
  'Profile & card': 'Profil et carte',
  'Profile or portfolio link (optional)': 'Lien de profil ou portfolio (facultatif)',
  'Profile page': 'Page de profil',
  'Profile published': 'Profil publié',
  'Profile type': 'Type de profil',
  Profiles: 'Profils',
  Publish: 'Publier',
  'Publish my profile': 'Publier mon profil',
  'Published by': 'Publiée par',
  'QR code created': 'QR code créé',
  'QR code deleted': 'QR code supprimé',
  'QR code saved': 'QR code enregistré',
  'QR code scan': 'Scan de QR code',
  'QR code scans': 'Scans de QR code',
  'QR codes': 'QR codes',
  'QR scans': 'Scans QR',
  'Read the API reference': "Lire la référence de l'API",
  Remote: 'Télétravail',
  'Remote possible': 'Télétravail possible',
  'Remove link': 'Retirer le lien',
  'Remove logo': 'Retirer le logo',
  'Remove rule': 'Retirer la règle',
  'Remove the password': 'Retirer le mot de passe',
  'Remove variant': 'Retirer la variante',
  'Replace logo': 'Remplacer le logo',
  'Reply by email': 'Répondre par e-mail',
  'Respond to this opportunity': 'Répondre à cette opportunité',
  Restore: 'Restaurer',
  'Revoke key': 'Révoquer la clé',
  'Revoke this key? Apps using it will stop working.':
    "Révoquer cette clé ? Les applications qui l'utilisent cesseront de fonctionner.",
  'Role and company': 'Poste et entreprise',
  'Role, technology, company…': 'Poste, technologie, entreprise…',
  'Row {r}: {reason}': 'Ligne {r} : {reason}',
  'Rule destination': 'Destination de la règle',
  'Rule type': 'Type de règle',
  'Rules are checked from top to bottom. The first one that matches wins; everyone else goes to the destination above.':
    "Les règles sont vérifiées de haut en bas. La première qui correspond l'emporte ; les autres visiteurs vont vers la destination ci-dessus.",
  'Rules run at the edge, in more than 300 cities, before the page even starts loading. Visitors never see a chooser screen.':
    "Les règles s'exécutent en périphérie du réseau, dans plus de 300 villes, avant même le chargement de la page. Les visiteurs ne voient jamais d'écran de choix.",
  'Same page for everyone': 'Même page pour tous',
  Save: 'Enregistrer',
  'Save and publish': 'Enregistrer et publier',
  'Save changes': 'Enregistrer',
  'Save contact': 'Enregistrer le contact',
  'Saved into the phone of anyone who scans your card. Leave empty what you do not want to share.':
    'Enregistré dans le téléphone de quiconque scanne votre carte. Laissez vide ce que vous ne voulez pas partager.',
  'Scan to open this profile': 'Scannez pour ouvrir ce profil',
  Search: 'Rechercher',
  'Search by name, title or destination': 'Rechercher par nom, titre ou destination',
  'Search links': 'Rechercher des liens',
  'Search or jump to…': 'Rechercher ou aller à…',
  'Second colour': 'Seconde couleur',
  'See analytics': 'Voir les statistiques',
  'Send a share of the remaining visitors to other pages and compare them in analytics. The main destination keeps {p}%.':
    "Envoyez une part des autres visiteurs vers d'autres pages et comparez-les dans les statistiques. La destination principale garde {p} %.",
  'Send message': 'Envoyer le message',
  'Send my application': 'Envoyer ma candidature',
  'Separate with commas.': 'Séparez par des virgules.',
  'Separate with commas. People search the directory with these words.':
    "Séparez par des virgules. L'annuaire est recherché avec ces mots.",
  Settings: 'Réglages',
  'Share a link to see visits arrive here in real time.':
    'Partagez un lien pour voir les visites arriver ici en temps réel.',
  'Share of traffic in percent': 'Part du trafic en pourcentage',
  'Share your profile link or QR card — messages people send through it land here.':
    'Partagez le lien de votre profil ou votre carte QR : les messages envoyés arrivent ici.',
  'Shop window poster': 'Affiche de vitrine',
  'Short links that know who is clicking.': 'Des liens courts qui savent qui clique.',
  'Short name': 'Nom court',
  Show: 'Afficher',
  'Show me in the public directory': "M'afficher dans l'annuaire public",
  'Sign in': 'Se connecter',
  'Sign in to your links, QR codes and inbox.': 'Connectez-vous à vos liens, QR codes et messages.',
  'Sign out': 'Se déconnecter',
  'Signed in as {email}.': 'Connecté en tant que {email}.',
  'Skill, industry, name…': 'Compétence, secteur, nom…',
  Skills: 'Compétences',
  'Smart routing': 'Routage intelligent',
  'Software, health, logistics…': 'Logiciel, santé, logistique…',
  'Solid ticket': 'Ticket plein',
  'Something else': 'Autre chose',
  Sort: 'Trier',
  'Source code': 'Code source',
  'Spring campaign landing page': 'Page de la campagne de printemps',
  Startup: 'Startup',
  Startups: 'Startups',
  Status: 'Statut',
  Tablet: 'Tablette',
  Tags: 'Tags',
  Technology: 'Technologie',
  'Their profile': 'Son profil',
  Theme: 'Thème',
  'They will reply to the email address you gave. No account needed on your side.':
    "La réponse arrivera à l'adresse e-mail indiquée. Aucun compte n'est nécessaire de votre côté.",
  'This QR code is real — scan it. Sign up to keep the short link and its analytics.':
    'Ce QR code est réel, scannez-le. Inscrivez-vous pour garder le lien court et ses statistiques.',
  'This link already has a password. Type a new one to replace it.':
    'Ce lien a déjà un mot de passe. Saisissez-en un nouveau pour le remplacer.',
  'This link does not lead anywhere.': 'Ce lien ne mène nulle part.',
  'This link has been turned off by its owner.': 'Ce lien a été désactivé par son propriétaire.',
  'This link has expired.': 'Ce lien a expiré.',
  'This link is protected': 'Ce lien est protégé',
  'This link reached its maximum number of visits.': 'Ce lien a atteint son nombre maximum de visites.',
  'This opportunity is closed.': 'Cette opportunité est fermée.',
  'This view could not load': "Cette vue n'a pas pu se charger",
  Title: 'Titre',
  'Top country': 'Premier pays',
  'Top links': 'Liens les plus cliqués',
  Traffic: 'Trafic',
  'Try a broader search, or publish your own profile so others can find you.':
    "Élargissez la recherche, ou publiez votre profil pour qu'on vous trouve.",
  'Try again': 'Réessayer',
  'Try another word or clear the filters.': 'Essayez un autre mot ou retirez les filtres.',
  'Try the demo': 'Essayer la démo',
  'Turn off after': 'Désactiver après',
  Type: 'Type',
  'Type a command or search your links…': 'Tapez une commande ou cherchez un lien…',
  'Unique visitors': 'Visiteurs uniques',
  'Unknown place': 'Lieu inconnu',
  Unlimited: 'Illimité',
  'Updating…': 'Mise à jour…',
  'Upload a photo or logo': 'Importer une photo ou un logo',
  'Use a key to create links and read analytics from your own code: Authorization: Bearer wrx_…':
    'Utilisez une clé pour créer des liens et lire les statistiques depuis votre code : Authorization: Bearer wrx_…',
  'Used {when}': 'Utilisée {when}',
  'Variant URL': 'URL de la variante',
  'Visitors from Morocco': 'Visiteurs depuis le Maroc',
  'Visitors must type it before being redirected.': "Les visiteurs doivent le saisir avant d'être redirigés.",
  'WRX shortens your links, turns them into designed QR codes, sends each visitor to the right page for their phone or country, and shows you every click as it happens. Your profile doubles as a business card that collects introductions.':
    'WRX raccourcit vos liens, les transforme en QR codes soignés, envoie chaque visiteur vers la bonne page selon son téléphone ou son pays, et vous montre chaque clic en direct. Votre profil sert aussi de carte de visite qui recueille les prises de contact.',
  'Wants to hire you': 'Veut vous recruter',
  Website: 'Site web',
  Websites: 'Sites',
  'Welcome back': 'Bon retour',
  'What is it about?': "De quoi s'agit-il ?",
  'What the person will do, what you offer, and how you decide.':
    'Ce que la personne fera, ce que vous offrez et comment vous choisissez.',
  'What they use': "Ce qu'ils utilisent",
  'What you are open to': 'Ce qui vous intéresse',
  'Where they are': 'Où ils se trouvent',
  'Who you are': 'Qui vous êtes',
  'Write to {name}': 'Écrire à {name}',
  'You are exploring the demo workspace with sample data. It resets every night.':
    "Vous explorez l'espace démo avec des données d'exemple. Il est réinitialisé chaque nuit.",
  'Your WRX profile is a page, a QR business card and a contact form in one. Startups post roles and fundraising calls, companies find talent, and every introduction lands in one inbox.':
    'Votre profil WRX est à la fois une page, une carte de visite QR et un formulaire de contact. Les startups publient des postes et des levées de fonds, les entreprises trouvent des talents, et chaque prise de contact arrive dans une seule boîte.',
  'Your contact details stay hidden in the directory; people write to you through the contact form.':
    "Vos coordonnées restent masquées dans l'annuaire ; on vous écrit via le formulaire de contact.",
  'Your email': 'Votre e-mail',
  'Your message goes straight to {name}.': 'Votre message est envoyé directement à {name}.',
  'Your name': 'Votre nom',
  'Your public page, QR business card and contact form. Startups and companies can create one page per brand.':
    'Votre page publique, votre carte de visite QR et votre formulaire de contact. Startups et entreprises peuvent créer une page par marque.',
  'iPhone visitors': 'Visiteurs iPhone',
  'posted {when}': 'publiée {when}',
  'send them to https://…': 'les envoyer vers https://…',
  'your message': 'votre message',
  '{d}% vs previous period': '{d} % par rapport à la période précédente',
  '{links} links created, {clicks} clicks routed and {profiles} public profiles so far.':
    '{links} liens créés, {clicks} clics redirigés et {profiles} profils publics à ce jour.',
  '{n} clicks': '{n} clics',
  '{n} clicks max': '{n} clics max',
  '{n} clicks per visitor': '{n} clics par visiteur',
  '{n} links': '{n} liens',
  '{n} links created.': '{n} liens créés.',
  '{n} open': '{n} ouvertes',
  '{n} responses': '{n} réponses',
  '{n} rows ready to import': '{n} lignes prêtes à importer',
  '{n} scans': '{n} scans',
  '{n} views': '{n} vues',
  '{p}% of all clicks': '{p} % des clics',
  '{r} rules, {v} variants': '{r} règles, {v} variantes',
  'Explore the live demo ': 'Explorer la démo',
  'Clicks per visitor': 'Clics par visiteur',
  'Choose a link': 'Choisir un lien',
  'Profiles ': 'Profils',
  "Connect: profiles, opportunities and an inbox": "Connect : profils, opportunités et messagerie",
  "Start for free": "Commencer gratuitement",
  "Shorten, route and track every link from the edge. Design QR codes that never need reprinting, and turn your profile into a card that collects introductions.": "Raccourcissez, routez et suivez chaque lien depuis la périphérie du réseau. Créez des QR codes qu'on ne réimprime jamais, et faites de votre profil une carte qui recueille les prises de contact.",
  "No credit card. The demo opens a workspace full of sample data.": "Sans carte bancaire. La démo ouvre un espace rempli de données d'exemple.",
  "The WRX analytics dashboard": "Le tableau de bord statistique de WRX",
  "Everything a link needs. Nothing it does not.": "Tout ce dont un lien a besoin. Rien de plus.",
  "One link can route, protect, measure and print. Each feature below is live in the demo.": "Un lien peut router, protéger, mesurer et s'imprimer. Chaque fonctionnalité ci-dessous est active dans la démo.",
  "Route every visitor": "Routez chaque visiteur",
  "Phones, countries and A/B splits decide the destination at the edge, before the page starts loading.": "Téléphone, pays et tests A/B décident de la destination en périphérie du réseau, avant le chargement de la page.",
  "Dynamic QR codes": "QR codes dynamiques",
  "Colours, logo, frame. Change the destination after printing.": "Couleurs, logo, cadre. Changez la destination après impression.",
  "Live analytics": "Statistiques en direct",
  "Clicks, unique visitors and QR scans as they happen.": "Clics, visiteurs uniques et scans QR en temps réel.",
  "Global by default": "Mondial par défaut",
  "Country and city for every click, without storing a single IP address.": "Pays et ville de chaque clic, sans stocker une seule adresse IP.",
  "An API for everything": "Une API pour tout",
  "Create links and read analytics from your own code. Documented with OpenAPI.": "Créez des liens et lisez les statistiques depuis votre code. Documentée avec OpenAPI.",
  "A card that opens doors": "Une carte qui ouvre des portes",
  "A public profile, a QR business card and a contact form in one.": "Un profil public, une carte de visite QR et un formulaire de contact réunis.",
  "Full-stack developer, React and Node.js": "Développeuse full-stack, React et Node.js",
  "Where people, startups and companies find each other.": "Là où personnes, startups et entreprises se trouvent.",
  "Startups post roles, co-founder searches and funding calls. Companies find talent. Every introduction lands in one inbox, with a status, so nothing gets lost.": "Les startups publient des postes, des recherches de cofondateur et des levées de fonds. Les entreprises trouvent des talents. Chaque prise de contact arrive dans une seule boîte, avec un statut : rien ne se perd.",
  "A searchable directory, filtered by skill, city and intent": "Un annuaire filtrable par compétence, ville et intention",
  "Opportunities with their own short link and QR code": "Des opportunités avec leur propre lien court et QR code",
  "Contact details stay private until you answer": "Vos coordonnées restent privées tant que vous ne répondez pas",
  "Your next link deserves better.": "Votre prochain lien mérite mieux.",
  "Create an account in ten seconds, or look around the demo first.": "Créez un compte en dix secondes, ou faites d'abord le tour de la démo.",
  "iPhone → App Store": "iPhone → App Store",
  "Morocco → French page": "Maroc → page en français",
  "50% → Pricing B": "50 % → Tarifs B",
  "Everyone else → Pricing": "Les autres → Tarifs",
  "A short link routing visitors to four destinations": "Un lien court qui route les visiteurs vers quatre destinations",
  "live": "en direct",
  "Product": "Produit",
  "Developers": "Développeurs",
  "Analytics": "Statistiques",
  "Resources": "Ressources",
  "All systems normal": "Tous les systèmes fonctionnent",
  "Open source on GitHub": "Open source sur GitHub",
  "sample data": "données d'exemple",
};
